### PR TITLE
Reformat using .prettierrc config

### PR DESCRIPTION
**Pull request by justin-calleja**

### CODE REVIEW

**Comment by harttle** [comment]
It's awesome to have code linting, but we should make it repeatable (so that I won't break the rule even if we do not use the same editor).
Such as providing a npm script and save that tool into `devDependencies`, so we can run `npm run lint` to check it. If you're not sure which one to use, I recommend eslint.

**Comment by justin-calleja** [comment]
I used prettier for code formatting (not linting). There's plenty that can be added considering today's tooling. The question is "does it warrant it?" - as in, I don't know how much more the project needs to grow.

For e.g. we could add Babel to support older Node.js versions (I'm using destructuring, arrow functions, const variables etc...). At first I tried to avoid doing so but then I figured "if this is going to be used for testing - we can make a reasonable assumption that the user can bump their version of Node.js if they have to (heck, I guess they could even run with babel-node)".

I changed the formatter's config to be in-line with your existing file's style (previous index.js). i.e. the use of single-quotes, spaces, and 4 space indentation. I think this file was formatted with vscode's default format on save (I don't usually use double quotes). I must have forgotten to save the file again after adding `.prettierrc`.

Later, I'll add an npm script which runs prettier on the code (and add prettier as a dev dependency).

Cheers

**Comment by harttle** [comment]
Sorry, I thought it was for linting. It's great with or without a npm script.

**Comment by justin-calleja** [comment]
No problem. It's actually very similar to linting with `--fix`. I have grow to be a bit dependent on it. Unfortunately, it has sometimes given me trouble when used in conjunction with linters. Still, I would really recommend integrating it with your editor of choice to format on save.

I'll add another issue to remind myself in the future to add the npm script (it won't stop users from committing code which is not formatted - but I had once hooked it up with husky (I believe) to add a git hook and basically format code automatically before commit).

**Pull request merged**
